name: '🐛 Bug Report'
description: Report a reproducible bug.
labels: ['possible bug']
body:
  - type: markdown
    attributes:
      value: '⚠️ Please read and follow the instructions before submitting an issue:'
  - type: markdown
    attributes:
      value: |
        - Read all our documentation. It may contain information that helps you solve your issue.
        - Ensure your issue isn't already reported.
        - If you aren't sure that the issue is caused by this package, please use [Stack Overflow](https://stackoverflow.com).
        - Ensure it isn't already fixed in the latest package version.
  - type: textarea
    id: description
    attributes:
      label: 'Describe the bug'
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 'To Reproduce'
      description: |
        Code snippet to reproduce, ideally if you can provide a live example in https://codesandbox.io/ sandbox or a repository that illustrates the issue.
        **If your problem is not reproducible, please file under Support or Usage Question**
    validations:
      required: false
  - type: textarea
    id: code-snippet
    attributes:
      label: 'Code snippet'
      render: js
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 'Expected behavior'
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: markdown
    attributes:
      value: Environment
  - type: input
    id: package-version
    attributes:
      label: 'Package Version'
      placeholder: 'e.g. 1.2.6'
  - type: input
    id: browser
    attributes:
      label: 'Browser'
      placeholder: 'e.g. Chrome, Safari'
  - type: input
    id: browser-version
    attributes:
      label: 'Browser Version'
      placeholder: 'e.g. 42'
  - type: input
    id: node-version
    attributes:
      label: 'Node.js Version'
      description: 'node --version'
      placeholder: 'e.g. 13.0.1'
  - type: input
    id: os
    attributes:
      label: 'OS'
      placeholder: 'e.g. iOS 16.0.2, OSX 12.6.0'
  - type: textarea
    id: other-version
    attributes:
      label: 'Additional Library Versions'
      placeholder: |
        e.g.
        React 16.7,
        React Native 0.58.0
      render: bash
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context/Screenshots'
      description: Add any other context about the problem here. If applicable, add screenshots to help explain.
      render: bash
    validations:
      required: false